FLINK-5725: Fix tox issues
https://jira.yelpcorp.com/browse/FLINK-5725

HACKATHON-39
To speed up gathering of details for a Flink cluster/job

When running paasta status, you are normally debugging something (something is broke)
You then may need to check related resources for the flink job such as yelpsoa/srv
Also when in a slack thread this information can useful to share in thread, reduce time to spot the issue

==========

Address review comment
```
FAILED tests/cli/test_cmds_status.py::TestPrintFlinkStatus::test_error_no_flink_config - AttributeError: 'NoneType' object has no attribute 'get_pool' FAILED tests/cli/test_cmds_status.py::TestPrintFlinkStatus::test_error_no_flink_overview - AttributeError: 'NoneType' object has no attribute 'get_pool' FAILED tests/cli/test_cmds_status.py::TestPrintFlinkStatus::test_successful_return_value - AttributeError: 'NoneType' object has no attribute 'get_pool'
```