FLINK-5725: Fix tests by populating flink_instance_config
https://jira.yelpcorp.com/browse/FLINK-5725

HACKATHON-39
To speed up gathering of details for a Flink cluster/job

When running paasta status, you are normally debugging something (something is broke)
You then may need to check related resources for the flink job such as yelpsoa/srv
Also when in a slack thread this information can useful to share in thread, reduce time to spot the issue

==========

Test failing with
```
>           flink_pool = flink_instance_config.get_pool()
E           AttributeError: 'NoneType' object has no attribute 'get_pool'
```

Fix by populating object

Remove duplication by moving object flink_instance_config to test ficture