use a string instead of a sentinel to get rid of a warning
this gets rid of:
```
PytestUnhandledThreadExceptionWarning: Exception in thread Thread-9 (_stream_docker_logs)

Traceback (most recent call last):
    File "[...]local_run.py", line 229, in _stream_docker_logs
        print(f"container [{container_id[:12]}]: {log_line}")
TypeError: '_SentinelObject' object is not subscriptable

```