FLINK-5725: Downgrade environment-tools
https://jira.yelpcorp.com/browse/FLINK-5725

HACKATHON-39
To speed up gathering of details for a Flink cluster/job

When running paasta status, you are normally debugging something (something is broke)
You then may need to check related resources for the flink job such as yelpsoa/srv
Also when in a slack thread this information can useful to share in thread, reduce time to spot the issue

==========

Was using latest
https://pypi.yelpcorp.com/simple/environment-tools/index.html

But error in build

ERROR: Could not find a version that satisfies the requirement environment-tools==1.2.2 (from versions: 1.1.0, 1.1.3)
ERROR: No matching distribution found for environment-tools==1.2.2

Updated to use version in output