FLINK-5725: Fix tox issues
https://jira.yelpcorp.com/browse/FLINK-5725

HACKATHON-39
To speed up gathering of details for a Flink cluster/job

When running paasta status, you are normally debugging something (something is broke)
You then may need to check related resources for the flink job such as yelpsoa/srv
Also when in a slack thread this information can useful to share in thread, reduce time to spot the issue

==========
paasta_tools/flink_tools.py:114: error: Function is missing a return type annotation

paasta_tools/flink_tools.py:125: error: TypedDict "FlinkDeploymentConfigDict" has no key 'spot'